/** Catálogo de iconos del hub (espejo del backend / frontend). */
export const HUB_ICONS = [
  { id: 'grid', name: 'Cuadrícula', glyph: '▦' },
  { id: 'home', name: 'Inicio', glyph: '⌂' },
  { id: 'building', name: 'Edificio', glyph: '▣' },
  { id: 'file', name: 'Documento', glyph: '▥' },
  { id: 'docs', name: 'Archivos', glyph: '📁' },
  { id: 'inbox', name: 'Bandeja', glyph: '▤' },
  { id: 'clipboard', name: 'Lista', glyph: '☰' },
  { id: 'check', name: 'Listo', glyph: '✓' },
  { id: 'chat', name: 'Chat', glyph: '💬' },
  { id: 'megaphone', name: 'Aviso', glyph: '📣' },
  { id: 'bell', name: 'Alerta', glyph: '🔔' },
  { id: 'calendar', name: 'Calendario', glyph: '📅' },
  { id: 'clock', name: 'Reloj', glyph: '🕐' },
  { id: 'users', name: 'Personas', glyph: '👥' },
  { id: 'user', name: 'Persona', glyph: '👤' },
  { id: 'star', name: 'Destacado', glyph: '★' },
  { id: 'heart', name: 'Favorito', glyph: '♥' },
  { id: 'link', name: 'Enlace', glyph: '🔗' },
  { id: 'globe', name: 'Web', glyph: '🌐' },
  { id: 'lock', name: 'Seguridad', glyph: '🔒' },
  { id: 'unlock', name: 'Abierto', glyph: '🔓' },
  { id: 'key', name: 'Acceso', glyph: '🔑' },
  { id: 'mail', name: 'Correo', glyph: '✉' },
  { id: 'phone', name: 'Teléfono', glyph: '☎' },
  { id: 'mobile', name: 'Móvil', glyph: '📱' },
  { id: 'book', name: 'Manual', glyph: '📖' },
  { id: 'books', name: 'Biblioteca', glyph: '📚' },
  { id: 'briefcase', name: 'Trabajo', glyph: '💼' },
  { id: 'chart', name: 'Métricas', glyph: '📊' },
  { id: 'trend', name: 'Tendencia', glyph: '📈' },
  { id: 'gift', name: 'Beneficios', glyph: '🎁' },
  { id: 'tool', name: 'Herramientas', glyph: '⚙' },
  { id: 'wrench', name: 'Soporte', glyph: '🔧' },
  { id: 'cloud', name: 'Nube', glyph: '☁' },
  { id: 'pin', name: 'Ubicación', glyph: '📍' },
  { id: 'map', name: 'Mapa', glyph: '🗺' },
  { id: 'bolt', name: 'Rápido', glyph: '⚡' },
  { id: 'shield', name: 'Política', glyph: '🛡' },
  { id: 'wallet', name: 'Pagos', glyph: '💳' },
  { id: 'money', name: 'Dinero', glyph: '💰' },
  { id: 'cart', name: 'Compras', glyph: '🛒' },
  { id: 'tag', name: 'Etiqueta', glyph: '🏷' },
  { id: 'flag', name: 'Bandera', glyph: '🚩' },
  { id: 'target', name: 'Objetivo', glyph: '🎯' },
  { id: 'rocket', name: 'Lanzamiento', glyph: '🚀' },
  { id: 'lightbulb', name: 'Idea', glyph: '💡' },
  { id: 'search', name: 'Buscar', glyph: '🔍' },
  { id: 'camera', name: 'Cámara', glyph: '📷' },
  { id: 'image', name: 'Imagen', glyph: '🖼' },
  { id: 'video', name: 'Video', glyph: '🎬' },
  { id: 'music', name: 'Música', glyph: '🎵' },
  { id: 'mic', name: 'Micrófono', glyph: '🎤' },
  { id: 'print', name: 'Impresión', glyph: '🖨' },
  { id: 'download', name: 'Descarga', glyph: '⬇' },
  { id: 'upload', name: 'Subida', glyph: '⬆' },
  { id: 'refresh', name: 'Actualizar', glyph: '🔄' },
  { id: 'sync', name: 'Sincronizar', glyph: '🔁' },
  { id: 'wifi', name: 'Red', glyph: '📶' },
  { id: 'laptop', name: 'Notebook', glyph: '💻' },
  { id: 'server', name: 'Servidor', glyph: '🖥' },
  { id: 'database', name: 'Datos', glyph: '🗄' },
  { id: 'code', name: 'Código', glyph: '</>' },
  { id: 'bug', name: 'Incidencia', glyph: '🐛' },
  { id: 'health', name: 'Salud', glyph: '🩺' },
  { id: 'leaf', name: 'Sustentable', glyph: '🌿' },
  { id: 'car', name: 'Movilidad', glyph: '🚗' },
  { id: 'plane', name: 'Viajes', glyph: '✈' },
  { id: 'train', name: 'Transporte', glyph: '🚆' },
  { id: 'coffee', name: 'Café', glyph: '☕' },
  { id: 'food', name: 'Comedor', glyph: '🍽' },
  { id: 'home-heart', name: 'Bienestar', glyph: '🏡' },
  { id: 'handshake', name: 'Acuerdo', glyph: '🤝' },
  { id: 'trophy', name: 'Logro', glyph: '🏆' },
  { id: 'medal', name: 'Reconocimiento', glyph: '🏅' },
  { id: 'fire', name: 'Urgente', glyph: '🔥' },
  { id: 'snow', name: 'Vacaciones', glyph: '❄' },
  { id: 'sun', name: 'Día', glyph: '☀' },
  { id: 'moon', name: 'Noche', glyph: '🌙' },
  { id: 'info', name: 'Info', glyph: 'ℹ' },
  { id: 'help', name: 'Ayuda', glyph: '?' },
  { id: 'warning', name: 'Atención', glyph: '⚠' },
  { id: 'plus', name: 'Nuevo', glyph: '+' },
  { id: 'edit', name: 'Editar', glyph: '✎' },
  { id: 'folder', name: 'Carpeta', glyph: '📂' },
  { id: 'note', name: 'Nota', glyph: '📝' },
  { id: 'id', name: 'Credencial', glyph: '🪪' },
  { id: 'badge', name: 'Insignia', glyph: '🎖' },
  { id: 'puzzle', name: 'Integración', glyph: '🧩' },
  { id: 'package', name: 'Paquete', glyph: '📦' },
  { id: 'box', name: 'Caja', glyph: '⬜' },
  { id: 'circle', name: 'Punto', glyph: '●' },
]

export function hubGlyph(icon) {
  return HUB_ICONS.find((o) => o.id === icon)?.glyph || '◉'
}

export const HUB_ICON_SIZES = [
  { id: 'sm', label: 'Chico', px: 28 },
  { id: 'md', label: 'Mediano', px: 36 },
  { id: 'lg', label: 'Grande', px: 48 },
]

export function resolveIconSize(linkSize, categorySize) {
  const s = linkSize || categorySize || 'md'
  return ['sm', 'md', 'lg'].includes(s) ? s : 'md'
}
