/** Iconos SVG mínimos para la botonera U (sin deps). */
export const NAV_ICONS = {
  muro: 'home',
  home: 'home',
  'mis-publicaciones': 'inbox',
  solicitudes: 'inbox',
  aprobaciones: 'check',
  alarma: 'alert',
  check: 'check',
  encuestas: 'clipboard',
  docs: 'file',
  conocimiento: 'file',
  agenda: 'calendar',
  calendar: 'calendar',
  oficina: 'grid',
  ayuda: 'help',
  help: 'help',
  politicas: 'shield',
  shield: 'shield',
  hub: 'grid',
  accesos: 'grid',
  chat: 'chat',
  guardados: 'bookmark',
  bookmark: 'bookmark',
  perfil: 'user',
  user: 'user',
  avisos: 'bell',
  bell: 'bell',
  asistente: 'sparkles',
  sparkles: 'sparkles',
  gift: 'gift',
  beneficios: 'gift',
  'beneficios.earn': 'sparkles',
  'mi-legajo': 'file',
  bienvenida: 'sparkles',
  organigrama: 'user',
  asistencia: 'pin',
  'mi-asistencia': 'pin',
  directorio: 'grid',
  espacios: 'calendar',
  building: 'calendar',
  licencias: 'clipboard',
  ausencias: 'list',
  ausentismos: 'list',
  clipboard: 'clipboard',
  list: 'list',
  more: 'menu',
  supervision: 'clipboard',
  'supervision.mis-tareas': 'list',
  'mi-equipo': 'user',
  users: 'user',
  pedidos: 'inbox',
  servicios: 'grid',
  'mi-desarrollo': 'sparkles',
  cultura: 'heart',
  heart: 'heart',
}

export function iconFor(key, iconHint) {
  if (iconHint && NAV_ICONS[iconHint]) return NAV_ICONS[iconHint]
  const k = String(key || '').toLowerCase()
  for (const [id, name] of Object.entries(NAV_ICONS)) {
    if (k.includes(id)) return name
  }
  return 'dot'
}
